version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    container_name: api_php_1
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - /tmp-deploy/uploads/admin-panel:/app/web/uploads
    ports:
      - '8001:80'
